//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonRemake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonRemake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_pokemon {
            get {
                object obj = ResourceManager.GetObject("all_pokemon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID,Name,Description,Use in Battle
        ///1,Potion,A spray-type medicine for wounds. It restores the HP of one Pokemon by just 20 HP,1
        ///.
        /// </summary>
        internal static string ItemTable {
            get {
                return ResourceManager.GetString("ItemTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Kalimba {
            get {
                object obj = ResourceManager.GetObject("Kalimba", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number,Name,Type_1,Type_2,Base_HP,Base_Atk,Base_Def,Base_Spec_Atk,Base_Spec_Def,Base_Spd,Base_Exp,Base_Exp_Type,Weight(kg)
        ///0,ERROR,0,0,0,0,0,0,0,0,0,0,0
        ///1,Bulbasaur,5,8,45,49,49,65,65,45,64,3,6.9
        ///2,Ivysaur,5,8,60,62,63,80,80,60,141,3,13
        ///3,Venusaur,5,8,80,82,83,100,100,80,208,3,100
        ///4,Charmander,2,-1,39,52,43,60,50,65,65,3,8.5
        ///5,Charmeleon,2,-1,58,64,58,80,65,80,142,3,19
        ///6,Charizard,2,10,78,84,78,109,85,100,209,3,90.5
        ///7,Squirtle,3,-1,44,48,65,50,64,43,66,3,9
        ///8,Wartortle,3,-1,59,63,80,65,80,58,143,3,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PkmTable {
            get {
                return ResourceManager.GetString("PkmTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tm Num,Name,Description,Type,Category,Power,Accuracy,PP,Priority
        ///1,Absorb,WIP,5,2,20,1,25,0
        ///2,Acid,WIP,8,2,40,1,30,0
        ///3,Acid Armor,WIP,8,3,-1,-1,20,0
        ///4,Agility,WIP,11,3,-1,-1,30,0
        ///5,Amnesia,WIP,11,3,-1,-1,20,0
        ///6,Aurora Beam,WIP,6,2,65,1,20,0
        ///7,Barrage,WIP,1,1,15,1,20,0
        ///8,Barrier,WIP,11,3,-1,-1,20,0
        ///9,Bide,WIP,1,1,-1,-1,10,1
        ///10,Bind,WIP,1,1,15,0.85,20,0
        ///11,Bite,WIP,16,1,60,1,25,0
        ///12,Blizzard,WIP,6,2,110,0.7,5,0
        ///13,Body Slam,WIP,1,1,85,1,15,0
        ///14,Bone Club,WIP,9,1,65,0.85,20,0
        ///15,Bonemerang,WIP,9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TmTable {
            get {
                return ResourceManager.GetString("TmTable", resourceCulture);
            }
        }
    }
}
